name: Publish Sample App

on: 
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: ./gradlew sample:assembleDebug
    - name: Rename apk
      run: mv android/sample/build/outputs/apk/debug/sample-debug.apk SampleApp-android.apk
    - name: Upload
      uses: skx/github-action-publish-binaries@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: 'SampleApp-android.apk'
